<a href="https://colab.research.google.com/github/SaiPooja6/GithubTest/blob/main/Copy_of_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0



# Creating all tensor flow with sample examples.

In [ ]:
#Creating a tensor with tf.constant
scalar = tf.constant(6)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
#Checking the number of dimensions of above tensor
scalar.ndim

0

In [ ]:
#Creating a tensor(vector)
vector = tf.constant([6,6])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 6], dtype=int32)>

In [ ]:
#Checking the dimension of a vector
vector.ndim

1

In [ ]:
#Creating a matrix
matrix = tf.constant([[6,6],
                      [7,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 6],
       [7, 7]], dtype=int32)>

In [ ]:
#Checking the dimension of the matrix
matrix.ndim

2

In [ ]:
#Creating a another matrix with 3 rows
another_matrix = tf.constant([[6.,6.,6.],
                              [7.,7.,7.],
                              [8.,8.,8.]],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[6., 6., 6.],
       [7., 7., 7.],
       [8., 8., 8.]], dtype=float16)>

In [ ]:
#Checking the dimension of the anothe rmatrix:
another_matrix.ndim

2

In [ ]:
#Creating a new tensor
tensor = tf.constant([[[6,6,6],
                      [6,6,6]],
                      [[7,7,7],
                       [7,7,7]],
                       [[8,8,8],
                        [8,8,8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[6, 6, 6],
        [6, 6, 6]],

       [[7, 7, 7],
        [7, 7, 7]],

       [[8, 8, 8],
        [8, 8, 8]]], dtype=int32)>

In [ ]:
#Checking the dimension of a tensor
tensor.ndim

3